name: Build and Serve Web

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Match Dockerfile's node:18-slim

    - name: Install dependencies
      run: cd frontend && npm install --production

    - name: Build project
      run: cd frontend && npm run build
      env:
        REACT_APP_GA4_MEASUREMENT_ID: ${{ secrets.REACT_APP_GA4_MEASUREMENT_ID }}

    - name: Serve static page
      run: |
        cd frontend
        npm install -g serve
        serve -s build -p 3000 &
        sleep 5
        curl http://localhost:3000
        pkill -f serve